Tab

diff --git a/change-hue b/change-hue
--- a/change-hue
+++ b/change-hue
@@ -5,33 +5,33 @@
 ## http://johnriselvato.com/how-to-edit-the-hue-of-a-video/
 
 if [[ ${1} ]]
-	then
-		if [[ -f ${1} ]]
-			then
-				INPUT_FILE=${1}
-			else
-				echo "${1} not found, or not a file."
-				exit 1
-		fi
-	else
-		echo "Specify the file to modify."
-		exit 1
+    then
+        if [[ -f ${1} ]]
+            then
+                INPUT_FILE=${1}
+            else
+                echo "${1} not found, or not a file."
+                exit 1
+        fi
+    else
+        echo "Specify the file to modify."
+        exit 1
 fi
 
 CHANGE_HUE()
 {
 for NUM in $(seq 9)
-	do
-		ffmpeg -i ${INPUT_FILE} -vf "hue=h=${NUM}000:b=-1:s=1" ./${INPUT_FILE}-${NUM}-h.png
-		ffmpeg -i ${INPUT_FILE} -vf "hue=H=${NUM}000:b=-1:s=1" ./${INPUT_FILE}-${NUM}-H.png
+    do
+        ffmpeg -i ${INPUT_FILE} -vf "hue=h=${NUM}000:b=-1:s=1" ./${INPUT_FILE}-${NUM}-h.png
+        ffmpeg -i ${INPUT_FILE} -vf "hue=H=${NUM}000:b=-1:s=1" ./${INPUT_FILE}-${NUM}-H.png
 done
 }
 
 
 if ! ffmpeg > /dev/null
-	then
-		CHANGE_HUE
-	else
-		echo "ffmpeg not found!"
-		exit 1
+    then
+        CHANGE_HUE
+    else
+        echo "ffmpeg not found!"
+        exit 1
 fi
diff --git a/wallpaper-grabber b/wallpaper-grabber
--- a/wallpaper-grabber
+++ b/wallpaper-grabber
@@ -38,41 +38,41 @@ WALLHAVEN_URL="https://wallhaven.cc/api/v1/search?q=${QUERY}&categories=${CATEGO
 
 wallhavenRequest()
 {
-	curl -sf ${WALLHAVEN_URL}\
-	| jq '.' | grep -Eoh 'https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'\
-	| xargs -l wget -nc -nv -P ${WALLPAPERS_DIR}
+    curl -sf ${WALLHAVEN_URL}\
+    | jq '.' | grep -Eoh 'https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b'\
+    | xargs -l wget -nc -nv -P ${WALLPAPERS_DIR}
 }
 
 if [[ ${1} ]]
-	then
-		QUERY="${1}"
-	else
-		echo -e "${WARN}Usage: wallpaper-grabber <topic> <directory>"
-		exit 1
+    then
+        QUERY="${1}"
+    else
+        echo -e "${WARN}Usage: wallpaper-grabber <topic> <directory>"
+        exit 1
 fi
 
 if [[ ${2} ]]
-	then
-		WALLPAPERS_DIR="${2}"
-		mkdir -p ${WALLPAPERS_DIR}
-	else
-		echo -e "${WARN}Usage: wallpaper-grabber <topic> <directory>"
-		exit 1
+    then
+        WALLPAPERS_DIR="${2}"
+        mkdir -p ${WALLPAPERS_DIR}
+    else
+        echo -e "${WARN}Usage: wallpaper-grabber <topic> <directory>"
+        exit 1
 fi
 
 if ! which ${REQUIREMENTS}>/dev/null
-	then
-		echo -e "${WARN}To run this program, you need the following packages installed: ${REQUIREMENTS}"
-		exit 1
+    then
+        echo -e "${WARN}To run this program, you need the following packages installed: ${REQUIREMENTS}"
+        exit 1
 fi
 
 echo -e " 🔎 ${INFO}Searching for ${QUERY} wallpapers..."
 wallhavenRequest
 
 if [[ ${?} -eq '0' ]]
-	then
-		echo -e "${GOOD}Wallpapers downloads finished!"
-	else
-		echo -e "${WARN}Page not found..."
-		exit 1
+    then
+        echo -e "${GOOD}Wallpapers downloads finished!"
+    else
+        echo -e "${WARN}Page not found..."
+        exit 1
 fi
